version: "1.0"

usage_steps:
  en:
    - "1. Select a folder to scan"
    - "2. Choose CSV output location"
    - "3. Configure scan rules (RDC, Image Sequence, MOV)"
    - "4. Click 'Start Processing'"
  zh_tw:
    - "1. 選擇要掃描的資料夾"
    - "2. 選擇CSV輸出位置"
    - "3. 配置掃描規則 (RDC, 影像序列, MOV)"
    - "4. 點擊開始處理"
  zh_cn:
    - "1. 选择要扫描的文件夹"
    - "2. 选择CSV输出位置"
    - "3. 配置扫描规则 (RDC, 影像序列, MOV)"
    - "4. 点击开始处理"

translations:
  en:
    window_title: "Hard Disk Scanner"
    select_scan_folder: "Scan Path:"
    select_csv_output: "CSV Output Path:"
    scan_rules: "Scan Rules:"
    rule_rdc: "Stop when finding .RDC files"
    rule_image_sequence: "Stop when finding image sequences"
    rule_mov: "Stop when finding files with extension:"
    start_processing: "Start Processing"
    processing: "Processing..."
    clear_log: "Clear Log"
    menu_help: "Help"
    menu_usage: "Usage Guide"
    menu_about: "About"
    language: "Language"
    status_ready: "Ready"
    status_processing: "Processing..."
    status_complete: "Complete"
    status_error: "Error: {}"
    error_no_scan_folder: "Error: Please select a scan folder"
    error_no_output_folder: "Error: Please select CSV output location"
    error_no_rules: "Error: Please select at least one scan rule"
    copyright: "HuHu © 2025. All rights reserved."
    version_text: '<a href="https://github.com/gumpcpy/scan-disk-tool">Version: {}</a>'
    select_folder_placeholder: "Please select scan path..."
    select_output_placeholder: "Please select CSV output location..."
    browse_button: "Browse..."
    log_scanning: "Scanning: {}"
    log_found_rdc: "Found RDC file: {}"
    log_found_image_sequence: "Found image sequence: {}"
    log_found_mov: "Found MOV file: {}"
    log_found_custom_extension: "Found {} file: {}"
    log_completed: "Scan completed. Found {} items."
    log_error: "Error during scan: {}"

  zh_tw:
    window_title: "硬碟掃描器"
    select_scan_folder: "掃描路徑："
    select_csv_output: "CSV輸出路徑："
    scan_rules: "掃描規則："
    rule_rdc: "找到.RDC結尾的檔案就停止"
    rule_image_sequence: "找到影像序列時就停止"
    rule_mov: "找到指定擴展名的檔案就停止："
    start_processing: "開始處理"
    processing: "處理中..."
    clear_log: "清空日誌"
    menu_help: "幫助"
    menu_usage: "使用說明"
    menu_about: "關於"
    language: "語言"
    status_ready: "就緒"
    status_processing: "處理中..."
    status_complete: "完成"
    status_error: "錯誤: {}"
    error_no_scan_folder: "錯誤：請選擇掃描路徑"
    error_no_output_folder: "錯誤：請選擇CSV輸出位置"
    error_no_rules: "錯誤：請至少選擇一個掃描規則"
    copyright: "HuHu © 2025。保留所有權利。"
    version_text: '<a href="https://github.com/gumpcpy/scan-disk-tool">版本：{}</a>'
    select_folder_placeholder: "請選擇掃描路徑..."
    select_output_placeholder: "請選擇CSV輸出位置..."
    browse_button: "瀏覽..."
    log_scanning: "掃描中：{}"
    log_found_rdc: "找到RDC檔案：{}"
    log_found_image_sequence: "找到影像序列：{}"
    log_found_mov: "找到MOV檔案：{}"
    log_found_custom_extension: "找到{}檔案：{}"
    log_completed: "掃描完成。找到 {} 個項目。"
    log_error: "掃描過程中發生錯誤：{}"

  zh_cn:
    window_title: "硬盘扫描器"
    select_scan_folder: "扫描路径："
    select_csv_output: "CSV输出路径："
    scan_rules: "扫描规则："
    rule_rdc: "找到.RDC结尾的文件就停止"
    rule_image_sequence: "找到影像序列时就停止"
    rule_mov: "找到指定扩展名的文件就停止："
    start_processing: "开始处理"
    processing: "处理中..."
    clear_log: "清空日志"
    menu_help: "帮助"
    menu_usage: "使用说明"
    menu_about: "关于"
    language: "语言"
    status_ready: "就绪"
    status_processing: "处理中..."
    status_complete: "完成"
    status_error: "错误: {}"
    error_no_scan_folder: "错误：请选择扫描路径"
    error_no_output_folder: "错误：请选择CSV输出位置"
    error_no_rules: "错误：请至少选择一个扫描规则"
    copyright: "HuHu © 2025。保留所有权利。"
    version_text: '<a href="https://github.com/gumpcpy/scan-disk-tool">版本：{}</a>'
    select_folder_placeholder: "请选择扫描路径..."
    select_output_placeholder: "请选择CSV输出位置..."
    browse_button: "浏览..."
    log_scanning: "扫描中：{}"
    log_found_rdc: "找到RDC文件：{}"
    log_found_image_sequence: "找到影像序列：{}"
    log_completed: "扫描完成。找到 {} 个项目。"
    log_found_mov: "找到MOV文件：{}"
    log_found_custom_extension: "找到{}文件：{}"
    log_error: "扫描过程中发生错误：{}"
